apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-test
  namespace: argocd
spec:
  project: workloads
  source:
    repoURL: https://github.com/andrelsyoo/app-sample-k8s-manifests
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: apps

